version: 2
python:
  # Install our python package before building the docs
  install: 
    - requirements: docs/requirements.txt
build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"
 
mkdocs:
  configuration: mkdocs.yml
 